[global]
mraauthor=["jotego"]

[parse]
sourcefile="bionicc.cpp"
# skip.Setnames=["bioniccbl2"]

[buttons]
names=[
    { names="Shoot,Arm" }
]

[dipsw]
rename=[
    { name="Bonus Life", to="Bonus" },
]

[ROM]
regions=[
    { name="maincpu", width=16, reverse=true },
    { name="gfx2", sequence=[0,4,1,5,2,6,3,7], start="JTFRAME_BA1_START" },
    { name="gfx1", start="FIX_START" },
    { name="gfx3", no_offset=true, start="JTFRAME_BA2_START" },
    { name="audiocpu", no_offset=true, start="JTFRAME_BA3_START" },
    { name="spritegen", width=32, reverse=true, no_offset=true },
    { name="mcu", start="JTFRAME_PROM_START" },
]

order=[ "maincpu",
    "gfx2", "gfx1",
    "gfx3",
    "audiocpu", "spritegen",
    "mcu","proms"
]