[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "1943.cpp" ]
skip.bootlegs=true

[buttons]
names=[
    { names="Shoot,Bomb" }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="audiocpu"},
    { name="mcu", skip=true },
    { name="gfx1" },
    { name="gfx2", sequence=[0,4,1,5,2,6,3,7], no_offset=true },
    { name="gfx3", no_offset=true },
    { name="gfx4", sequence=[0,4,1,5,2,6,3,7], no_offset=true },
    { name="tilerom", no_offset=true },
    { name="proms", sequence=[4,7,0,6,1,2,10,3,11,9,8,5], no_offset=true },
]

order=[ "maincpu", "audiocpu", "gfx1",
    "tilerom", "gfx2", "gfx3", "gfx4",
    "proms"
]