[global]
mraauthor=["jotego"]

[parse]
sourcefile="kchamp.cpp"
skip.setnames=[
    # won't boot
    "karatevs",
]

[buttons]
Names = [ { names="left(2),right(2),up(2),bottom(2)"} ]

[dipsw]
bitcnt = 8
delete = [ "Unused", "Unknown" ]

[ROM]
regions = [
    { name="audiocpu", start="SND_START" },

    { name="gfx1", start="CHAR_START", width=16, sort_even=true },
    { name="gfx2", start="OBJ_START", no_offset=true },
    { name="proms", start="JTFRAME_PROM_START" }
]

order = [
    "maincpu", "audiocpu",
    "gfx1", "gfx2", "proms"
]

splits = [
    { region="maincpu", offset=0xa000, min_len=0x4000, setnames=[
        "kchampvs",
        "kchampvs2",
        "kchampvs3",
        "kchampvs4",
    ] },
]

blanks = [
    { region="gfx2", offset=0xc000, len=0x4000 },
]

# It isn't clear how the ROM decryption works for the first
# four instructions. It is safe to just skip over them
patches = [
    { setnames=["kchampvs", "kchampvs3", "kchampvs4", "karatevs", ], offset=0, value="69 6e B4" },
]