[global]
mraauthor=["jotego"]

[parse]
sourcefile="vulgus.cpp"
skip.setnames=[ "vulgusa" ]
# vulgusa is flipped relative to the others


[buttons]
core=2 # max number of buttons supported by the core
names=[
    { names="Shoot,Bomb" }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="chars", start="JTFRAME_BA2_START", reverse=true },
    { name="sprites", width=16, sequence=[0,2,1,3] },
    { name="tiles", width=32, sequence=[0,2,4,4,1,3,5,5], start="JTFRAME_BA3_START" },
    { name="proms", start="JTFRAME_PROM_START", sequence=[0,1,2,3,5,4,0,0,6,7] },
]

order=["maincpu","audiocpu","chars", "sprites", "tiles", "proms" ]