[global]
mraauthor=["jotego"]

[parse]
sourcefile="vulgus.cpp"

[buttons]
core=2 # max number of buttons supported by the core
names=[
    { names="Shoot,Bomb" }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="audiocpu", start=$JTFRAME_BA1_START },
    { name="gfx1", start=$JTFRAME_BA2_START },
    { name="gfx3", width=16, sequence=[0,2,1,3] },
    { name="gfx2", width=32, sequence=[0,2,4,4,1,3,5,5], start=$JTFRAME_BA3_START },
    { name="palproms", start=$JTFRAME_PROM_START },
]

order=["maincpu","audiocpu","gfx1", "gfx3", "gfx2",
    "palproms",
    "charprom","tileprom", "sprprom", "proms"
]