[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "tigeroad.cpp" ]
skip.bootlegs=true
skip.Setnames=["bballs","bballsa","pushman","pushmana", "pushmans", "pushmant",
    "tigeroad","tigeroadb","tigeroadu","toramich"]

[buttons]
names=[
    { names="Low Gear,High Gear" }
]

[ROM]
regions=[
    { name="maincpu", width=16, reverse=true },
    { name="bgmap", reverse=true, start="JTFRAME_BA1_START" },
    { name="tiles", sequence=[3,0,4,1,5,2], width=16, start="SCR_START" },
    { name="audiocpu", start="JTFRAME_BA2_START" },
    { name="text",no_offset=true, start="JTFRAME_BA3_START", reverse=true },
    { name="spritegen", width=32, reverse=true, no_offset=true },
    { name="proms", start="JTFRAME_PROM_START" },
    { name="mcu", start="MCU_START" },
]

order=[ "maincpu",
    "bgmap", "tiles",
    "audiocpu", "sample",
    "text", "spritegen",
    "proms", "mcu"
]