[global]
mraauthor=["jotego"]

[parse]
sourcefile="tigeroad.cpp"
skip.Setnames=["bballs","bballsa","pushman","pushmana", "pushmans", "pushmant",
    "tigeroad","tigeroadb","tigeroadu","toramich"]

[buttons]
names=[
    { names="Low Gear,High Gear" }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="text",no_offset=true, start=$CHAR_START },
    { name="bgmap", sequence=[0,0], no_offset=true },
    { name="tiles", sequence=[4,5,6,7,0,1,2,3], no_offset=true },
    { name="spritegen", sequence=[3,2,1,0], no_offset=true },
]

order=[ "maincpu", "audiocpu", "text", "bgmap", "tiles", "spritegen", "proms", "mcu" ]