[global]
mraauthor=["jotego"]

[parse]
sourcefile="tigeroad.cpp"
skip.Setnames=["bballs","bballsa","pushman","pushmana", "pushmans", "pushmant","f1dream","f1dreamb","f1dreamba"]

[buttons]
names=[
    { names="Attack,Jump" },
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="audiocpu", start=$JTFRAME_BA1_START },
    { name="text",no_offset=true, start=$JTFRAME_BA2_START, reverse=true },
    { name="bgmap", sequence=[0,0], reverse=true, start=$JTFRAME_BA3_START },
    { name="tiles", sequence=[4,0,5,1,6,2,7,3], width=16 },
    { name="spritegen", width=32, no_offset=true },
]

order=[ "maincpu",
    "audiocpu", "sample",
    "text", "spritegen",
    "bgmap", "tiles",
    "proms"]