[global]
mraauthor=["jotego"]

[parse]
sourcefile="tigeroad.cpp"
skip.Setnames=["bballs","bballsa","pushman","pushmana", "pushmans", "pushmant","f1dream","f1dreamb","f1dreamba"]

[buttons]
names=[
    { names="Attack,Jump" },
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="text",no_offset=true, start=$CHAR_START },
    { name="bgmap", sequence=[0,0], no_offset=true },
    { name="tiles", sequence=[4,5,6,7,0,1,2,3], no_offset=true },
    { name="spritegen", no_offset=true },
]

order=[ "maincpu", "audiocpu", "sample", "text", "bgmap", "tiles", "spritegen", "proms"]