[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "bublbobl.cpp" ]
skip.setnames=[
    # Blank screen
    "boblbobl", "bbredux", "bub68705", "bublboblb",
    # Garbled graphics, ripoff
    "dland",
    # No graphics
    "boblcave",
    # 8749 MCU - doesn't boot on MAME
    "bub8749",
    # Tokio hardware - Nees MCU support
    "bublboblp",
    "tokio",
    "tokioo",
    "tokiou",
    # wrong inputs and no MCU?
    "sboblbobl",
    "sboblbobla",
    "sboblboblb",
    "sboblboblc",
    "sboblbobld",
    # untested
    "sboblboble",
    "sboblboblf"
]
main_setnames=["tokiob"]

[buttons]
names=[
    { names="Shoot,Jump" }
]

[dipsw]
bitcnt = 16
delete = [ "Unused", "Unknown", "Mode" ]
defaults = [
    { value="ff,ff" },
]
extra = [
    { machine="bublbobl", name="Language", Options="English,Japanese", Bits="0" },
    { machine="bublbobl", name="Operation", Options="Test,Game", Bits="2" },
]
Rename = [
    {Name="ROM Type",To="Type"},
]

[ROM]
regions = [
    { name="maincpu", No_offset=true, reverse=true },
    { name="subcpu", No_offset=true, reverse=true,   start="SUB_START" },
    { name="audiocpu", No_offset=true, reverse=true, start="SND_START" },
    { name="mcu", No_offset=true, reverse=true,      start="MCU_START" },
    { name="gfx1", width=16, start="GFX_START", sequence=[0,6,1,7,2,8,3,9,4,10,5,11] },
    { name="gfx1", width=16, start="GFX_START", setname="tokiob", sequence=[0,8,1,9,2,10,3,11,4,12,5,13,6,14,7,15] },
    { name="proms", start="JTFRAME_PROM_START"},
    { name="plds", skip=true },
]

order = [
    "maincpu", "subcpu", "audiocpu", "mcu", "gfx1", "proms"
]