[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "aliens.cpp", "thunderx.cpp" ]

[buttons]
names = [
    { names="Shoot standing,Shoot crouching" }
]

[dipsw]
delete = [ "Unused", "Unknown" ]
rename=[ {name="Continue Limit (1Player/2Players)", to="Max cont", values=["5 and 4","3 and 2"] }, ]

# rename = [
#     {  name="Difficulty 1 (Game)", To="Gameplay" },
#     {  name="Difficulty 2 (Strength)", To="Strength" },
#     {  name="Allow Continue", To="Continue" },
# ]

[ROM]
regions = [
    { name="maincpu" }, # First 32kB go to $8000, the rest are banked at $6000
    { name="audiocpu",  start="JTFRAME_BA1_START" },
    { name="k007232",   start="PCM_START" },
    { name="k052109",   start="JTFRAME_BA2_START", width=32 }, # tiles
    { name="k051960",   start="JTFRAME_BA3_START", width=32, reverse=true }, # sprites
    { name="proms",     start="JTFRAME_PROM_START" } # last one is the priority encoder
]

order = [ "maincpu", "audiocpu", "k007232", "k052109", "k051960", "proms" ]

# Skips the RAM check
patches = [ { setname="aliens", offset=0x2806a, value="AE AE AE" } ]