[global]
mraauthor=["jotego"]

[parse]
sourcefile="sidearms.cpp"
skip.Setnames=[
    "dyger",
    "dygera",
    "turtship",
    "turtshipj",
    "turtshipk",
    "turtshipkn",
    "turtshipko",
    "twinfalc",
    "whizz",
]

[buttons]
core=3 # max number of buttons supported by the core
names=[
    { names="Fire-Left,Fire-Right,Power" },
]