[global]
mraauthor=["jotego"]

[parse]
sourcefile="sidearms.cpp"
skip.Setnames=[
    "dyger",
    "dygera",
    "turtship",
    "turtshipj",
    "turtshipk",
    "turtshipkn",
    "turtshipko",
    "twinfalc",
    "whizz",
]

[buttons]
core=3 # max number of buttons supported by the core
names=[
    { names="Fire-Left,Fire-Right,Power" },
]

[dipsw]
bitcnt=19   # number 19 is freeze, active low
defaults=[
    { value="fc,ff,ff" },
]

[rom]
regions=[
    { name="maincpu", reverse=true  },
    { name="audiocpu", reverse=true  },
    { name="user1", reverse=true  }, # starfield
    { name="gfx1"   },
    # GFX2
    { name="gfx2"  },
    { machine="sidearms", name="gfx2", width=16, sequence=[0,4,1,5,2,6,3,7] },
    # GFX3
    { name="gfx3" },
    { machine="sidearms", name="gfx3", width=16, sequence=[0,4,1,5,2,6,3,7] },
    { name="gfx4"   },
    { name="proms"   },
]

order = [ "maincpu","audiocpu", "user1",
"gfx1", "gfx2", "gfx3", "gfx4", "proms" ]