[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "1942.cpp", "vulgus.cpp" ]
skip.setnames=[
    "1942abl",
    "1942p",
    "1942fpa",
    "1942hc64",
    "1942gx64",
    "galagax",
]

[dipsw]
extra=[
    { machine="vulgus", name="Flip Screen", options="Off,On", bits="16" },
]

[header]
info = """ Header to identify the PCB type
        Byte 0 = 0 for 1942, 1 for Vulgus
        Byte 1 = XOR with flip
"""
data = [
    { machine="vulgus", offset=0, data="01" },
    # vulgusa is flipped relative to the others
    # { setname = "vulgusa", offset=1, data="01" },
]

[buttons]
names=[
    { machine="1942",   names="Shoot,Roll" },
    { machine="vulgus", names="Shoot,Bomb" }
]

[ROM]
regions=[
    {                   name="audiocpu", start="JTFRAME_BA1_START" },
    # 1942
    { machine="1942",   name="maincpu", no_offset=true, sequence=[0,1,2,3,3,4] },
    { machine="1942",   name="gfx1", start="JTFRAME_BA2_START", reverse=true },
    { machine="1942",   name="gfx3", width=16, sequence=[2,0,3,1] },
    { machine="1942",   name="gfx2", width=32, sequence=[0,2,4,4,1,3,5,5], start="JTFRAME_BA3_START" },
    { machine="1942",   name="palproms", start="JTFRAME_PROM_START" },
    # Vulgus
    { machine="vulgus", name="maincpu", no_offset=true },
    { machine="vulgus", name="chars", start="JTFRAME_BA2_START", reverse=true, rename="gfx1" },
    { machine="vulgus", name="sprites", width=16, sequence=[0,2,1,3], rename="gfx3" },
    { machine="vulgus", name="tiles", width=32, sequence=[0,2,4,4,1,3,5,5], start="JTFRAME_BA3_START", rename="gfx2" },
    { machine="vulgus", name="proms", start="JTFRAME_PROM_START", sequence=[0,1,2,3,5,4,0,0,6,7] },

]

order=["maincpu","audiocpu","gfx1", "gfx3", "gfx2",
    "palproms",
    "charprom","tileprom", "sprprom", "proms"
]