[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "blktiger.cpp" ]
skip.bootlegs=true

[buttons]
names=[
    { names="Attack,Jump" }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true, sequence=[1,2,3,4,0]},
    { name="audiocpu" },
    { name="chars", sequence=[0,0], no_offset=true },
    { name="tiles", sequence=[2,3,0,1], no_offset=true },
    { name="sprites", no_offset=true },
    { name="mcu" },
    { name="proms" }
]

order=[
    "maincpu", "audiocpu", "chars",
    "tiles", "sprites", "mcu", "proms"
]