[global]
mraauthor=["jotego"]

[parse]
sourcefile="commando.cpp"
# The first byte in these games is encoded, opposite to
# other games
skip.Setnames=["sinvasnb","mercenario","commandob"]

[buttons]
names=[
    { names="Shoot,Grenade" }
]

# Need to reorder it in the core
# so regions don't get merged
[ROM]
regions=[
    { name="audiocpu", start=$JTFRAME_BA1_START },
    { name="gfx1", start=$JTFRAME_BA2_START },
    { name="gfx3", width=16, sequence=[0,3,1,4,2,5] },
    { name="gfx2", width=32, sequence=[0,1,2,2,3,4,5,5], start=$JTFRAME_BA3_START },
    { name="proms" },
    { name="plds", skip=true },
]

order=[ "maincpu", "audiocpu", "gfx1",
    "gfx3", "gfx2", "proms" ]