[global]
mraauthor=["jotego"]

[parse]
sourcefile="higemaru.cpp"

[buttons]
names=[
    { names="Action" }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="gfx1", reverse=true },
    { name="gfx2", width=16, no_offset=true },
]

order=["maincpu","gfx1","gfx2","proms"]