[global]
mraauthor=["jotego"]

[parse]
sourcefile="higemaru.cpp"

[buttons]
names=[
    { names="Action" }
]

[ROM]
regions=[
    { name="maincpu" },
    { name="chars", reverse=true, start="JTFRAME_BA1_START" },
    { name="sprites", width=16, start="JTFRAME_BA2_START" },
]

order=["maincpu","chars","sprites","proms"]