name: Compile all cores

on:
  workflow_dispatch:

  repository_dispatch:
    types: rebuild

  push:
    branches:
      - master
    paths:
      - cores/**
      - modules/**

jobs:
  list_cores:
    runs-on: ubuntu-latest
    outputs:
      cores: ${{ steps.generate-matrix.outputs.cores }}
    steps:
    - uses: actions/checkout@v2
    - id: generate-matrix
      run: |
        cd cores
        CORES=$(tree -J -d -L 1 | jq -c '.[0].contents | map(.name)')
        echo $CORES
        echo "cores=${CORES}" >> $GITHUB_OUTPUT

  compile_cores:
    runs-on: ubuntu-latest
    container:
      image: jotego/jtcore13
    needs:
      - list_cores
    strategy:
      fail-fast: false
      matrix:
        core: ${{ fromJSON(needs.list_cores.outputs.cores) }}
        target: [ sidi, mist, pocket ]
    steps:
      - uses: actions/checkout@v3
      - id: submodules
        run: |
          git config --global --add safe.directory /__w/jtcores/jtcores
          git submodule init
          git submodule update --depth 1
          cd modules
          cd jt12
          git submodule init
          git submodule update --depth 1
          cd ../..
      - id: compile
        run: |
          pwd
          echo $SHELL
          source setprj.sh
          jtcore {{ matrix.core }} --target {{matrix.target}} --nodbg

